# Generated by Django 4.0.6 on 2022-07-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_store_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='owner',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='owner'),
        ),
    ]
