# Generated by Django 4.0.6 on 2022-07-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_store_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='status',
            field=models.CharField(default='in_review', max_length=100, verbose_name='status'),
        ),
    ]
