# Generated by Django 4.0.6 on 2022-07-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_store_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('deactivated', 'deactivated'), ('in_review', 'in_review')], default='in_review', max_length=100, verbose_name='status'),
        ),
    ]
